### Test Teacher
GET http://localhost:7878/v2/api/teacher/test
Accept: application/json

### Registrar Profesor/(a) por Ms-Teacher
POST http://localhost:7878/v2/api/teacher/save
Content-Type: application/json

{
  "name":"Juan Carlos",
  "subject":"Matematicas"
}

### Registrar Profesor/(a) por Ms-Gateway
POST http://localhost:8181/ms-teacher/v2/api/teacher/save
Content-Type: application/json

{
  "name":"Juan Carlos",
  "subject":"Matematicas"
}

### Obtener todos los profesores
GET http://localhost:7878/v2/api/teacher/all
Accept: application/json

### Obtener profesor por Id
GET http://localhost:7878/v2/api/teacher?teacherId=1
Accept: application/json

### Actualizar Profesor/(a) por Ms-Teacher
PUT http://localhost:7878/v2/api/teacher/update?teacherId=1
Content-Type: application/json

{
  "name":"Juan Carlos12",
  "subject":"Lenguaje"
}